
INSERT INTO public.bases_legendarios (instagram_handle, nome, regiao) VALUES
('legendariosbrasil', 'Nacional', 'Nacional'),
('legendariossaopaulo', 'São Paulo', 'SP'),
('legendariosreset', 'Reset', NULL),
('legendarios3colinas', '3 Colinas', NULL),
('legendariossatl', 'SATL', NULL),
('legendariosglobal', 'Global', 'Internacional'),
('legendariospt', 'Portugal', 'Internacional'),
('legendariosmontenegro', 'Montenegro', 'Internacional'),
('legendarios.spcapital', 'SP Capital', 'SP'),
('legendariosvaledosfortes', 'Vale dos Fortes', NULL),
('legendariosusa', 'USA', 'Internacional'),
('legendariosabusca', 'A Busca', NULL),
('legendariosostepr', 'Oeste PR', 'PR'),
('legendariosalmaguerreira', 'Alma Guerreira', NULL),
('legendariosvaledosol', 'Vale do Sol', NULL),
('legendariospara', 'Pará', 'PA'),
('legendariosmaringa', 'Maringá', 'PR'),
('legendariostheharbour', 'The Harbour', NULL),
('legendarioslamantiqueira', 'La Mantiqueira', NULL),
('legendariosarapongas', 'Arapongas', 'PR'),
('legendariosdivinopolis', 'Divinópolis', 'MG'),
('legendariosaguasprofundas', 'Águas Profundas', NULL),
('legendariosdourados', 'Dourados', 'MS'),
('legendariosceara', 'Ceará', 'CE'),
('legendariosuberlandiaarocha', 'Uberlândia A Rocha', 'MG'),
('legendariosapucaranapr', 'Apucarana PR', 'PR'),
('legendariosaguadepedra', 'Água de Pedra', NULL),
('legendariosbetim', 'Betim', 'MG'),
('legendarios_sp_valedoparaiba', 'SP Vale do Paraíba', 'SP'),
('legendariossouloffire', 'Soul of Fire', NULL),
('legendariosatitude', 'Atitude', NULL),
('legendariosbauru', 'Bauru', 'SP'),
('legendarioseaglesnest', 'Eagle''s Nest', NULL),
('legendarioslitoral', 'Litoral', NULL),
('legendarios.es', 'Espírito Santo', 'ES'),
('legendarisitalia', 'Itália', 'Internacional'),
('legendarioscostaricaoficial', 'Costa Rica Oficial', 'Internacional'),
('legendariosvaledossinos', 'Vale dos Sinos', 'RS'),
('legendarioscoracaovalente', 'Coração Valente', NULL),
('legendariosbrasilia', 'Brasília / DF', 'DF'),
('legendariosgoias', 'Goiás', 'GO'),
('legendariostrackpantanal', 'Track Pantanal / MS', 'MS'),
('legendarisforcaselvagem', 'Força Selvagem', NULL);
