// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilknzgupnswyeynwpovj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlsa256Z3VwbnN3eWV5bndwb3ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0NzEyMzEsImV4cCI6MjA4NjA0NzIzMX0.dEr0MFzKtbkqxXu0m5dvMPDZWlB-uddw2UNsUP3UUKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});